### ISSUE TITLE
Does not generate the source folder

### ISSUE THREAD

**Issue by TonyDroidd** [EvolSoft/PharTools#1]
(Windows)

Does not generate the source folder :new_moon_with_face: 

The console say:

Extracting...
Extracted in C:\Program Files\PharTools!

But the source folder is not in that directory

**Comment by Flavius12** [comment]
Try to run cmd.exe as Administrator. Windows allows you to write files on Program Files directory only if you have admin privileges

**Comment by TonyDroidd** [comment]
it is running as Administrator

**Comment by Flavius12** [comment]
Can you post the command you run and can you post the phar file you want to extract?

**Comment by TonyDroidd** [comment]
phartools -e C:\Users\usuario\Documents\PocketMine-MP\plugins\NPE.phar

**Comment by Flavius12** [comment]
Try to copy the Phar file in PharTools directory and then extract it

**Comment by TonyDroidd** [comment]
ok, ill try

**Comment by Flavius12** [comment]
Does it work?

**Comment by TonyDroidd** [comment]
No :o

**Comment by Flavius12** [comment]
Can you send the phar you want to extract? And are you sure you are running Windows Command Shell as administrator?
