### ISSUE TITLE
Website/domain doesn't work anymore

### ISSUE THREAD

**Issue by strarsis** [EvolSoft/PharTools#6]
I followed the download link to the website: https://www.evolsoft.tk/phartools/download/
But the domain doesn't exist anymore.

**Comment by Flavius12** [comment]
Hi and thank you for your interest in this project. Unfortunately evolsoft.tk was registered as a free domain and I've never understood why freenom.org suddenly deleted my domain and doesn't let me register it again.
Keep in mind that EvolSoft was born only as a personal hobby. It was just a dream that never realized. Everything I developed for my "dream company" was developed as an hobby and distributed for free as donationware. I never wanted to earn a lot of money from these projects but however I hoped to receive donations at least to buy a paid domain and renew it yearly to continue developing my ideas and my projects and share them with you.
Back to your question you can download PharTools from: https://sourceforge.net/projects/phartools/files/v2.1/
Thanks again for your interest in this project
